# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
  - release
  - develop

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                GIT_COMMIT=$(git rev-parse --short HEAD)

                echo "GIT_COMMIT: ${GIT_COMMIT}"

                #
                # set env variable to allow next task to consume
                #
                echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: 'polarity-acr'
              repository: 'polarity-TN-BTC-Gateway'
              command: buildAndPush
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(Build.SourceBranchName)
                $(GIT_COMMIT)